all:
	./ChatScript local build0=files0.txt
	./ChatScript local build1=filesKora.txt reset
	./ChatScript local


build:
	./ChatScript local build0=files0.txt
	./ChatScript local build1=filesKora.txt reset


server:
	./ChatScript local build0=files0.txt
	./ChatScript local build1=filesKora.txt reset
	./ChatScript

clean:
	rm ../USERS/log-*
	rm ../USERS/topic*
